services:
  kernloos:
    image: toonolfke/kernloos:latest
    container_name: kernloos
    restart: unless-stopped
    ports:
      - "3020:3000"
    environment:
      - ORIGIN=https://kernloos.be
      - NODE_ENV=production
