services:
  kernloos:
    image: toonolfke/site-dev:latest
    container_name: kernloos
    restart: unless-stopped
    ports:
      - "3020:3000"
    environment:
      - ORIGIN=https://site-dev.olfke.be
      - NODE_ENV=production
